#!/bin/bash
#SBATCH -p pq
#SBATCH -A Research_Project-T127870
### Change for job   ### ### ### ### ###
#SBATCH --job-name=220SiGeDFTVasp
#SBATCH --time=24:00:00
#SBATCH --nodes=1
### ### ### ### ### ### ### ### ### ###
#SBATCH --ntasks-per-node=16
#SBATCH -D .
#SBATCH --export=ALL
#SBATCH --mail-user=ah1365@exeter.ac.uk
#SBATCH --mail-type=END
#SBATCH --output=220SiGeDFTVasp.out
#SBATCH --error=220SiGeDFTVasp.err
### ### ### ### ### ### ### ### ### ###

NNODES=$SLURM_JOB_NUM_NODES
PPN=16
np=$(($SLURM_JOB_NUM_NODES*16))
export OMP_NUM_THREADS=1 # changing this breaks paralisation

### ### ### ### ### ### ### ###

#VASP_STD="/lustre/home/ah1365/bin/vasp_std"


module purge
module load intel/2023a

#module load gompi

export MPI=$(($NNODES*$PPN))

export WORK_DIR=`pwd`

export JOB_HOSTNAME=`hostname`

export JOB_TIME_START=`date -u`

cd $WORK_DIR

echo "Si Bulk DFT energetics calculations using VASP\n"
echo "This script is running on ${JOB_HOSTNAME} in ${WORK_DIR}\n"
echo "Job started on: ${JOB_TIME_START}\n"

vasp_std

export JOB_TIME_END=`date -u`

echo "Job ended on: ${JOB_TIME_END}\n"
